"""empty message

Revision ID: 327c132bb53b
Revises: a5ba07843447
Create Date: 2021-03-07 16:32:27.945593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327c132bb53b'
down_revision = 'a5ba07843447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=150), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drone')
    # ### end Alembic commands ###
